version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: cpall-pms-back-office-react
    command: yarn start
    # restart: always
    volumes:
      - .:/app:delegated
    ports:
      - 9008:3000
    environment:
      BROWSER: none # for windows subsystem linux
      # HTTPS: 'true'
